version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: restaurants-db
    restart: always
    environment:
      MYSQL_DATABASE: restaurants_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: restaurants-api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/restaurants_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mi_clave_super_secreta_para_firmar_tokens_123456
      JWT_EXPIRATION: 86400000
      GEOAPIFY_API_KEY: 17488dd471c44547a6fa73ee2c0698fb

volumes:
  mysql_data: